Implemented back to top button
AdvisorySG/mentorship-page pull request #354
Opened 2021-09-24 14:27 UTC by IvanFengJK

#349

2021-09-24 15:32 UTC, amirulraziqi commented on src/components/Styles.js
> +`
Do add a white fill for the up-arrow.
![image](https://user-images.githubusercontent.com/66960654/134700112-095b37c3-416e-4381-8ba2-c6efb7dc631a.png)

2021-09-25 04:50 UTC, amirulraziqi commented on src/components/ScrollButton.js
> +export default ScrollButton;
@wei2912 LGTM, but requesting your review still

2021-09-25 04:50 UTC, amirulraziqi reviewed
@wei2912 Apart from the white fill, LGTM! 

Still, requesting your review for this specific PR.

2021-09-25 05:03 UTC, amirulraziqi reviewed
@wei2912 Apart from white fill and `package-lock.json`, LGTM!

Still, requesting for your review here

2021-09-25 05:03 UTC, amirulraziqi commented on package-lock.json
> +      "name": "mentorship-page",
@IvanFengJK Revert any changes made to this file before pushing to github. `package-lock.json` should be left untouched.

2022-01-26 15:48 UTC, amirulraziqi requested changes
We'd rather the `package-lock.json` file not be changed. Could you uncommit changes to the package-lock.json file before pushing once more?

Other than that, everything else LGTM

2022-08-30 22:43 UTC, wei2912 commented
Superseded by https://github.com/AdvisorySG/mentorship-page/pull/509.

2022-08-30 22:43 UTC, closed without merging