Add dropdown
AdvisorySG/mentorship-page pull request #435
Opened 2022-04-17 07:21 UTC by luodan01

Close #399

2022-04-17 10:35 UTC, amirulraziqi requested changes
Referencing the two screenshots below, a few changes to be made:

<img width="837" alt="image" src="https://user-images.githubusercontent.com/66960654/163710532-d69c53ac-dc85-41d1-8c3e-0f1d87507c20.png">
<img width="783" alt="image" src="https://user-images.githubusercontent.com/66960654/163710586-505718a9-c17a-4d75-ab64-2d0266e13a45.png">

1. Do keep the styles consistent. The font size for mentor bio before and after clicking the "Read More" button is not the same. 
2. When searching up "Product Owner" or any other search query, the words 'product owner' is not highlighted within the bio snippet, but is highlighted in the full biography (after clicking read more). Might have something to do with the snippet. @wei2912 Any ideas?

Do make the required changes! Otherwise, I think it's good!

2022-04-17 10:35 UTC, amirulraziqi commented on src/globals.d.ts
> +declare module "@react-show-more-text";
There shouldn't be a need for this since types have already been declared for the library. Can remove.

2022-04-17 10:35 UTC, amirulraziqi commented on package.json
> -    "@mui/material": "^5.5.0",
You can revert this to 5.5.0, since the upgrade isn't needed for this PR.

2022-04-17 10:58 UTC, wei2912 commented
On the highlighting, some biographies exceed 1000 characters which is the max size of the snippet. Hence, for now we'll need to stick to the following:
1. Display the snippet (up to 200 chars, with highlighting) when collapsed
2. Display the full bio (no limit on chars, with no highlighting) when expanded

As to the issue Raziq pointed out, this is likely to do with the read more library truncating away the `em` tags. Would be good if we can find a way to preserve them... Otherwise we'll just have to stick to no highlighting for both collapsed and expanded.

2022-04-22 03:03 UTC, amirulraziqi requested changes
Looking almost complete! 

Apart from reverting the package version as commented, will need you to remove this new submodule you just added - `app-search-demo-react`.

2022-04-22 03:03 UTC, amirulraziqi commented on package.json
> +    "@mui/material": "^5.6.1",
This package should be reverted ack to 5.5.0, as per previously requested!

2022-04-24 15:45 UTC, wei2912 commented
Made a couple of changes outside of rebasing involving changing the snippet so that the punctuation displays where the snippet was located and trims any punctuation to make it look nice and neat. I have linked a bunch of issues that can be closed by this.

We may want to consider deploying `fillHighlights` for a somewhat more permanent fix to https://github.com/AdvisorySG/mentorship-page/issues/440. Unfortunately, this would require `snippet` and `raw` to be returned for every field, which is probably going to bog up the requests.

2022-04-24 16:20 UTC, amirulraziqi approved these changes
Looks good!

2022-04-24 16:26 UTC, merged