README update
AdvisorySG/mentorship-page pull request #548
Opened 2022-11-18 13:48 UTC by Hackin7

2022-12-10 02:09 UTC, wei2912 requested changes
Generally looks accurate and clear to me, though capitalisation in some areas seem to be inconsistent (e.g. "Airtable" vs "AirTable"). Also, try to avoid using `here` and then adding a link; it would be clearer to use the title of the page, which gives more information about what that page provides. See rest of comments in this review.

2022-12-10 02:09 UTC, wei2912 commented on README.md
> +`git clone https://github.com/AdvisorySG/mentorship-page.git`
This should be block code for ease of copying.

Also, please specify the `$` sign infront of the commands (following usual Bash command prompt conventions)

2022-12-12 03:58 UTC, Hackin7 commented
I made most of the changes requested. For now I put Node v18 as the version, so have to wait for https://github.com/AdvisorySG/mentorship-page/pull/534 to be pushed first

I realised that it may be important to add is Contributing guidelines, but I'm not too sure how to best do it for now. For now I linked the Ghost Theme CONTRIBUTING.md (which I think is quite good), but I also added in a small section about `prettier`, and that they should run it before submitting the PR. (Especially since there's a check for it)

2022-12-13 02:28 UTC, wei2912 commented
> For now I linked the Ghost Theme CONTRIBUTING.md (which I think is quite good), but I also added in a small section about `prettier`, and that they should run it before submitting the PR. (Especially since there's a check for it)

The `CONTRIBUTING.md` document is meant to be org-wide but it hasn't been updated in a while (think I wrote it back in 2020...). Feel free to make any changes on the Ghost repository and create a new PR here to add a copy to here.

2022-12-30 04:54 UTC, Hackin7 commented on README.md
> +Before submitting the Pull Request, make sure to run `prettier` to format the code for readability purposes.
For now I've added a section about running prettier manually (if commiting to github directly), hopefully it is useful for new developers to the repo who may not know about the hook

2023-02-27 14:19 UTC, wei2912 commented
Blocked by https://github.com/AdvisorySG/mentorship-page/pull/559

2023-03-17 14:24 UTC, wei2912 commented
Somehow pushing from my copy to your branch causes all these extra commits to pop up (instead of the branch adopting the actual commits of the `master` branch)... apologies for that

2023-03-17 14:28 UTC, wei2912 requested changes

2023-03-17 14:28 UTC, wei2912 commented on README.md
>  You don’t have to ever use `eject`. The curated feature set is suitable for small and middle deployments, and you shouldn’t feel obligated to use this feature. However we understand that this tool wo
Same for "Available Scripts". A lot of these aren't really relevant (they were artifacts from Create React App).

2024-06-22 16:43 UTC, closed without merging