Rough outline of FAQ Page with Collapsible Questions
AdvisorySG/mentorship-page pull request #581
Opened 2023-03-27 16:07 UTC by Hackin7

![image](https://user-images.githubusercontent.com/18213722/227999167-de63b545-15e0-4137-a4b6-7463056d9ef3.png)

Questions can be input in via JSON (may need to figure out a better way to store the JSON?)

2023-04-06 14:23 UTC, wei2912 commented
Would be good if we can switch to using https://mui.com/material-ui/react-accordion/ for the dropdowns.

2023-04-10 16:28 UTC, Hackin7 commented
![image](https://user-images.githubusercontent.com/18213722/230945892-2dfdd857-1174-454f-923b-079db1f6b8a6.png)

To add relevant questions. Not too sure where to put the questions (or if it even makes sense to separate it from the page tsx)

2023-05-10 02:08 UTC, wei2912 commented on pages/faq.tsx
> +                <Typography>{question}</Typography>
Could we bold the question?

2023-05-10 02:08 UTC, wei2912 requested changes
LGTM, but would be good if we could import the JSON object from another file, rather than hardcode into `pages/faq.tsx`.

2023-05-10 02:09 UTC, wei2912 approved these changes
Ignore "Request Changes" in the previous comments.

2023-05-10 02:09 UTC, merged