adjust width on faq
AdvisorySG/mentorship-page pull request #787
Opened 2024-06-25 04:28 UTC by ykIsCoding

2024-07-08 13:14 UTC, wei2912 commented
Converting to draft while MPT-106 is in progress.

2024-12-29 09:26 UTC, wei2912 commented
@ykIsCoding See feedback by @jcc-kh at https://github.com/AdvisorySG/mentorship-page/issues/776#issuecomment-2564656740

Also, do rebase your branch - it's a bit outdated (since we took a while to review this...)

2024-12-29 09:28 UTC, wei2912 requested changes
See above.

2025-01-07 06:36 UTC, ykIsCoding commented
<img width="713" alt="image" src="https://github.com/user-attachments/assets/de52c7e9-f0f7-489a-a5c8-8c8abd5ab20b" />
done

2025-01-19 14:07 UTC, wei2912 commented
Manually merged in https://github.com/AdvisorySG/mentorship-page/commit/d260bb11360bfdfc58f66ba7ebfd0871743b4a7f. Some changes were made as the branch is outdated due to migration to page router.

2025-01-19 14:07 UTC, closed without merging